### ISSUE TITLE
Feature: Support for folder (rather than file) selection

### ISSUE THREAD

**Issue by the-moog** [crahan/ipyfilechooser#1]
I've created a patch for this if you are interested.

**Comment by crahan** [comment]
Thank you for your interest! 

Please feel free to make a pull request and I'll review.

**Comment by majulier** [comment]
I could use this feature.  :)

**Comment by crahan** [comment]
@majulier, @the-moog would it be an acceptable workaround if you could leave the filename blank and then press the select button to select the currently active folder?

**Comment by majulier** [comment]
That would work great for me.

**Comment by the-moog** [comment]
I'm not very good at GitHub. I've never created a pull request (just tried and I click create pull request it just jumps to "compare changes") Instead I've put my version of the code [here](https://nextcloud.cropwell.net/index.php/s/NCLEP4yTj9AscM6), you can merge that and review.

**Comment by the-moog** [comment]
I *think* I just created a pull request....

**Comment by the-moog** [comment]
And now even Travis is happy with it....

**Comment by crahan** [comment]
Thanks for the feedback and pull request. I'll take a look and see how i can merge. 

I might have to copy/paste your Windows drive code into my current updated version (which already has support for selecting folders and marking the default value as selected).

**Comment by crahan** [comment]
I added a new test branch (https://github.com/crahan/ipyfilechooser/tree/default_select_fix) which adds support for select_default=True as a parameter. When set to True, it takes the values for 'path' and 'filename' and applies them as the selected values.

The new branch also adds support for selecting a folder. If you leave the filename blank it will select the current folder you're in. If you enter a value in the filename field that matches a folder name, the select or change button will be disabled.

I will be adding a few more changes first before I push out a new packaged version to PyPi, but if you like you can take a peek at the new branch to see if it functions as expected. One of the things I still want to add is Windows drive letter support but I need to install Jupyter on Windows first so I can test.

**Comment by crahan** [comment]
Version 0.3.0 has been pushed to https://pypi.org/project/ipyfilechooser/. 

To select a folder, simply leave the filename field blank. If a filename is entered that matches an existing folder the select/change button will be disabled to make the user aware of the conflict.
