### ISSUE TITLE
Provide a way to filter file list 

### ISSUE THREAD

**Issue by shek2994** [crahan/ipyfilechooser#12]
Provide a way to pass the file filter pattern. Suppose on selecting a directory, there may be 1000s of files. But user is interested to list only a particular set of files ex: *.json.

**Comment by crahan** [comment]
Thanks for the suggestion. I'll try and get this added in a future update.

**Comment by giswqs** [comment]
This would be a nice feature to add. Either through or function or GUI. I guess a function is probably easier to implement than a GUI.

**Comment by crahan** [comment]
`filter_pattern` property has been added (based on https://docs.python.org/3/library/fnmatch.html) and https://github.com/crahan/ipyfilechooser/releases/tag/v0.4.0 has been released to PyPi and conda-forge.
