### ISSUE TITLE
Adding ipyfilechooser to conda-forge

### ISSUE THREAD

**Issue by giswqs** [crahan/ipyfilechooser#19]
It would be nice to have this package available on [conda-forge](https://conda-forge.org/feedstocks/). Here is the [instruction](https://github.com/conda-forge/staged-recipes#getting-started) to add a package to conda-forge. I can help in this regard if needed. Thanks.

**Comment by giswqs** [comment]
@crahan I have creatred the [meta.yaml](https://gist.github.com/giswqs/2298cb3ed189b6641c7e4cd608b48017) for you. This was created using `conda skeleton pypi ipyfilechooser` with some additional edits. You just need to fork [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes) and add a ipyfilechooser folder with the meta.yaml and LICENSE to the [recipes](https://github.com/conda-forge/staged-recipes/tree/master/recipes) folder. Submit a pull request and wait for the review and approval.

**Comment by crahan** [comment]
That's awesome. Thank you! I'll try and get a pull request out as soon as possible.

**Comment by crahan** [comment]
Working on it now. I'll post an update once the PR has been submitted.

**Comment by crahan** [comment]
Here we go: https://github.com/conda-forge/staged-recipes/pull/11297

**Comment by giswqs** [comment]
@crahan Thanks for your prompt action. I saw that the pull request has been merged. It should be available on conda-forge soon. It might take a few hours. Congrats!

**Comment by crahan** [comment]
Thank you for the suggestion and the help on this!
