### ISSUE TITLE
Add support for windows drive letters

### ISSUE THREAD

**Issue by the-moog** [crahan/ipyfilechooser#2]
I've created a patch for this too

**Comment by crahan** [comment]
Feel free to submit a pull request!

**Comment by crahan** [comment]
Apologies for the delay. The below solution is now available in the branch. It'll add any available drive letters at the end of the drop down list (but remove the drive letter that's already there as part of the path calculation). I'll try and package a new release asap.

<img width="551" alt="Screen Shot 2019-12-03 at 02 53 31" src="https://user-images.githubusercontent.com/172588/70013502-2b018480-1578-11ea-8866-b77e417ffff2.png">
<img width="546" alt="Screen Shot 2019-12-03 at 02 53 42" src="https://user-images.githubusercontent.com/172588/70013503-2b018480-1578-11ea-8f2c-ea738a2a589a.png">

**Comment by crahan** [comment]
Version 0.3.0 has been pushed to https://pypi.org/project/ipyfilechooser/. 

On Windows the dropdown menu will add any additional drives to the bottom of the list.
