### ISSUE TITLE
Include license in the source distribution

### ISSUE THREAD

**Issue by synapticarbors** [crahan/ipyfilechooser#20]
It would be nice to include the license file in the source distribution. The mechanism I usually see is using a `MANIFEST.in` with the appropriate entry.

**Comment by crahan** [comment]
Thanks for pointing that out @synapticarbors. I'll be sure to include the `LICENSE` file via `MANIFEST.in` with the next release.

**Comment by crahan** [comment]
I've submitted a pull request (https://github.com/conda-forge/staged-recipes/pull/12413) for the updated v0.3.5 version which now includes the `LICENSE` file in `MANIFEST.in`. I'll mark this as resolved.
