### ISSUE TITLE
use_dir_icons not working on Linux

### ISSUE THREAD

**Issue by giswqs** [crahan/ipyfilechooser#21]
The dir icon is not showing up on my Linux machine. Any advice? Thanks. 
```
import os
from ipyfilechooser import FileChooser

home_dir= os.path.expanduser('~')
# Create and display a FileChooser widget
fc = FileChooser(home_dir)
fc.default_filename = 'output.html'
fc.use_dir_icons = True

display(fc)
```
![](https://i.imgur.com/rXZsmw7.png)

**Comment by crahan** [comment]
The folder icon is rendered using unicode character `\U0001F4C1` (https://www.fileformat.info/info/unicode/char/1f4c1/index.htm). Can you verify which font is being used to render the text? It looks like support for that particular character is missing in the font that's being used.

**Comment by giswqs** [comment]
How to check which font is being used to render by the notebook?

**Comment by crahan** [comment]
I think right clicking on the area that's affected and then selecting the equivalent of `inspect element` for your particular browser will allow you to view the CSS for that section and see what font is being used. I'm not aware of an easier way to find the active font unfortunately.

**Comment by giswqs** [comment]
The Chrome browser shows `font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;`

![](https://i.imgur.com/RUtxOuy.png)

**Comment by crahan** [comment]
So your browser will go through that list until it hits a font that matches. It's hard to say which font is being used exactly that is missing the unicode character. I'll see about making the folder icon an optional feature that can be disabled or changed for a next release.

**Comment by giswqs** [comment]
I can set `fc.use_dir_icons = False` to disable folder icons, but I would love to show the icons if possible. 

I am using [Manjaro Linux KDE](https://manjaro.org/download/).

**Comment by crahan** [comment]
I was thinking that making the folder icon configurable would allow users to select an alternative unicode character that does work with their particular font setup. Disabling the icon does indeed work using the `fc.use_dir_icons` parameter already, as you indicated.

Just to rule out Chrome, can you try using Firefox (or another browser) and see if things are the same there?

**Comment by giswqs** [comment]
Interesting! It works with Firefox, but not Chrome.

![](https://i.imgur.com/2XuOYmr.png)

**Comment by giswqs** [comment]
As I am using ipyfilechooser as one of the dependencies for my [geemap](https://github.com/giswqs/geemap) package, I can not assume the all users will be using Firefox. For the time being, I will just set `fc.use_dir_icons = False`. I will turn it back on in the future if the icon issue can be resolved.

**Comment by crahan** [comment]
Interesting indeed. There's still a number of potential reasons why this might be though. So, using the developer tools in Firefox (right click and select 'Inspect element') you can check what font is actually being used to render the text.

<img width="576" alt="Screen Shot 2020-05-10 at 21 23 45" src="https://user-images.githubusercontent.com/172588/81508507-c4417d80-9304-11ea-9dc4-b9132e806143.png">

Can you check Chrome to see if `Computer styles` has any information about what font the browser is actually using to render the text? I believe it'll be near the bottom under a 'Rendered fonts` heading (e.g. https://makandracards.com/makandra/59967-css-how-to-find-out-the-rendered-font-in-chrome).

**Comment by crahan** [comment]
> As I am using ipyfilechooser as one of the dependencies for my [geemap](https://github.com/giswqs/geemap) package, I can not assume that all users will be using Firefox. For the time being, I will just set `fc.use_dir_icons = False`. I will turn it back on in the future if the icon issue can be resolved.

The folder icon solution does indeed rely heavily on a font being installed that supports the unicode character, which in turn also depends on the OS being used. A combination of both browser and underlying OS makes it somewhat of an unreliable solution.

I will leave this issue open for now though and see if I can find a more reliable solution to this.

**Comment by giswqs** [comment]
Interesting to see both are using `Bitstream Vera Sans Mono`.

Firefox:
![](https://i.imgur.com/cKz39Zr.png)

Chrome:
![](https://i.imgur.com/SDJc7lL.png)

**Comment by crahan** [comment]
That's definitely strange. I'll leave this open for now.

**Comment by giswqs** [comment]
This is demo for using ipyfilechooser in my [geemap](https://github.com/giswqs/geemap/blob/master/examples/notebooks/21_export_map_to_html_png.ipynb) Python package. This would be not possible without ipyfilechooser. Thank you!

![](https://i.imgur.com/rJuXH4a.gif)

**Comment by crahan** [comment]
That is amazing! This really just started out as a small project to scratch an itch. So great to see others getting some value out of this! And such an awesome project you've built!

**Comment by giswqs** [comment]
It seems this folder icon issue has been resolved. I can now see the icon on my Linux machine. Thank you. 

![](https://i.imgur.com/1AGleyd.png)
