### ISSUE TITLE
Select only folder

### ISSUE THREAD

**Issue by MariDani** [crahan/ipyfilechooser#26]
Hi everyone, I am creating small GUI in Jupyter lab including your file chooser widget. I need to only select folder path (not file path) I know I don't have to choose the file now, but I am afraid that I might confuse my users if they need to choose the file or not.  So I was wondering if it would be possible to disable the file choosing option and leave it only for the folder?

**Comment by crahan** [comment]
Hi @MariDani, the `dev` branch provides that functionality. You can checkout that version to use the `show_only_dirs` which will remove the file input field and allow you to select a folder instead. I need to refactor a few more things before I publish a new release, but you should be able to use the current `dev` version without any issues.

**Comment by crahan** [comment]
There's one small caveat and that is (only in macOS Safari) if you rapidly change the `.show_only_dirs` property while the filechooser dialog is visible (i.e. expanded) it will at some point mess up the layout. But if you initialize the dialog with the `show_only_dirs` parameter set (or in any other web browser) you will not experience any errors.

**Comment by MariDani** [comment]
Great, thank you!

**Comment by crahan** [comment]
I've pushed out a new release to get the folder-only functionality out there. It's up on PyPi now (https://pypi.org/project/ipyfilechooser/) and you can download v0.3.5 from https://github.com/crahan/ipyfilechooser/releases/tag/v0.3.5 as well.
