### ISSUE TITLE
Inherit from ValueWidget, for ipython_blocking?

### ISSUE THREAD

**Issue by bryceschober** [crahan/ipyfilechooser#28]
I discovered this awesome `FileChooser` and [the `ipython_blocking` module](https://github.com/kafonek/ipython_blocking) at the same time, and currently, I have to do some extra work to help them get along, as in https://github.com/kafonek/ipython_blocking/issues/6. So, it would be nice if `FileChooser` could inherit from `ValueWidget` or some other more seamless method of integration...

**Comment by crahan** [comment]
I'm guessing you require the option to retrieve the current selected file/folder through other Python modules and `ValueWidget` provides that functionality through the `get_interact_value` function?

Just thinking out loud, but `FileChooser` has a 'selected' property which already returns the selected path and file as a single string. Would it suffice to inherit from `ValueWidget` and implement `get_interact_value` to simply return that 'selected' property or would more be required to support what you need?

**Comment by crahan** [comment]
@bryceschober https://github.com/crahan/ipyfilechooser/releases/tag/v0.4.0 has now been released which inherits from `ValueWidget` and supports `get_interact_value()`.
