### ISSUE TITLE
default/selected

### ISSUE THREAD

**Issue by majulier** [crahan/ipyfilechooser#3]
When the widget first comes up, if there is a default_path and default_file could you please put those where the string "No file selected" currently is?  (or make selected_path and selected_file writeable?)  This is a total nit.  This is a great widget regardless.

**Comment by crahan** [comment]
Thanks for the suggestion and kind words. I'll try and update asap.

**Comment by crahan** [comment]
I added a new test branch (https://github.com/crahan/ipyfilechooser/tree/default_select_fix) which adds support for `select_default=True` as a parameter. When set to True, it takes the values for 'path' and 'filename' and applies them as the selected values.

I also added support for selecting a folder. If you leave the filename blank it will select the current folder you're in. If you enter a filename that matches a folder name, the select or change button will be disabled.

I will be adding a few more changes first before I push out a new packaged version to PyPi, but if you like you can take a peek at the new branch to see if it functions as expected.

**Comment by crahan** [comment]
Version 0.3.0 has been pushed to https://pypi.org/project/ipyfilechooser/ which adds support for `select_default=True` as a parameter.
