### ISSUE TITLE
Only allow access to a specific directory and sub-directories

### ISSUE THREAD

**Issue by giswqs** [crahan/ipyfilechooser#35]
Would it be possible to restrict file chooser to only access a specific directory and sub-directories only rather than the entire system directory? The reason for this is that I am developed a web app that allows users to select and display geospatial data. The web app can be deployed to a web server. It would be a security risk if users are allowed to browse the entire system directory of a web server.

https://user-images.githubusercontent.com/5016453/103163498-a447c700-47cc-11eb-97d7-a8be4e2ad4d2.mp4

**Comment by crahan** [comment]
Sounds like a good idea. I'll see about adding that as an option.

**Comment by crahan** [comment]
@giswqs I'm almost done implementing this but I had one question.

Would you like the value displayed next to the buttons when applying the selection to show a stripped version of the path? For example, if the `top_folder` is set to `/home/jdoe`, should a selection for `/home/jdoe/folderA/file.txt` display the full path or a stripped down version like `/jdoe/folderA/file.txt` (so it doesn't hint at the underlying folder structure on the web server)?

The value returned by the `selected` property will always return the full path of course.

**Comment by giswqs** [comment]
@crahan Thanks for working on this. I think the stripped version of the path is a better choice for reducing security risk.

**Comment by crahan** [comment]
I've released an intermediate version with the fix for https://github.com/crahan/ipyfilechooser/issues/38. One additional question as I've been trying to solution this is if the selected path and filename values returned by the widget should be the full path on the server or the restricted value?

For example, if `/var/www/application/` is the `top_folder` value the user can not navigate past, would selecting `/data/example.txt` in the widget return `/var/www/application/data/example.txt` as the selected value or `/data/example.txt`?

It sounded from your request that you would want to have everything restricted and hidden as much as possible as to not allow the users to navigate around the web server or give away any information regarding the server's folder structure beyond the restricted folder. My assumption is that these requirements extend to the actual value returned by the widget as well.

Please let me know if anything is unclear.

**Comment by giswqs** [comment]
Many thanks for the fix! v0.4.3 works like a charm. Regarding the file path, it is fine to return the full path as long as the user cannot navigate past the restricted directory. I would prefer the full path `/var/www/application/data/example.txt` as the selected value because I need it to be passed into other functions for further processing. Thanks.

**Comment by giswqs** [comment]
I made a video tutorial for using ipyfilechooser with [ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet). https://youtu.be/wxUZiWnHrhw

https://user-images.githubusercontent.com/5016453/114407146-1c68ab80-9b76-11eb-8d3a-5ceffd7cd98e.mp4

**Comment by crahan** [comment]
Hi @giswqs, I've finally finished implementing this feature and a test version of the code can be found in the https://github.com/crahan/ipyfilechooser/tree/root_folder branch.

When you specify a `sandbox_path` parameter the pathlist dropdown and label will show a sandboxed or shortened version of the selected path and navigating to a folder beyond the `sandbox_path` is not possible anymore. However, `.selected`, `.value`, and `selected_path` will still return the full path.

Without the sandbox parameter:

<img width="534" alt="Screen Shot 2021-09-06 at 23 22 00" src="https://user-images.githubusercontent.com/172588/132261526-58439f0f-e106-4e43-98ed-eaa960f1266d.png">

With the `sandbox_path` parameter:

<img width="524" alt="Screen Shot 2021-09-06 at 22 57 39" src="https://user-images.githubusercontent.com/172588/132261535-9677e6f1-f069-4392-b0c3-5c4b1597c59a.png">

If you have some time to test and confirm all is working as you'd expect, that would help a lot as this was a rather large change.

**Comment by crahan** [comment]
With the sandbox functionality I also added restrictions to using `\`, `/` at the start and end of filenames, as well as `..\` and `../` anywhere inside filenames to ensure users can not use the filename field to create a path that would map to a folder outside of the sandbox.

**Comment by giswqs** [comment]
@crahan Thanks a lot for implementing this. It works as expected when passing the `sandbox_path` during the filechooser creation. It would be even better if the `sandbox_path` can be set after the filechooser has been created. See the example below. I am not sure if it is feasible and how difficult it is to implement it. In my video demo above, the filechooser has been created in advance for the users using `os.getcwd()` as the initial path. It would be nice if users can set the `sandbox_path` afterwards because it would be challenging for users to modify the GUI source code. 

https://colab.research.google.com/drive/1C4GpAhe8_bKd14En3Kh975eElL_D9rOB?usp=sharing

```
fc3 = FileChooser('/content/sample_data')
fc3.sandbox_path = '/content'  #no effect
fc3
```

**Comment by crahan** [comment]
That should be no problem. I just need to think about how to properly handle setting `path` and `sandbox_path` properties that don't line up. I'm thinking to:

1. throw an exception when a `filechooser` object is created with a `path` and `sandbox_path` that don't align
2. trigger a warning when either property is changed on an existing `filechooser` object which results in `path` and `sandbox_path` not to align anymore and then leave the current value unchanged

**Comment by crahan** [comment]
The `root_folder` branch has been updated with the option to update the `sandbox_path` on an existing filechooser.

Please note that doing so will first check if the `default_path` and new `sandbox_path` value can work together (one falls under the other). If not, then it throws an error and the assignment will fail. If both paths work together then the new `sandbox_path` is set and the filechooser is reset. This can be done at any time, so before or after the filechooser is displayed in the notebook.

Similar checks have been added for other properties as well to ensure `path` and `filename` parameters are valid prior to updating filechooser object properties with those values.

**Comment by giswqs** [comment]
Thanks for the quick implementation. It seems to work well if `sandbox_path` is set before filechooser is displayed. However, if `sandbox_path` is set after the filechooser is displayed and users already select a filepath outside the `sandbox_path`, the filechooser might still show the system directory. I also got the index out of bound errors at first try, but I could not reproduce it when trying to taking the screencast. 

https://colab.research.google.com/drive/1C4GpAhe8_bKd14En3Kh975eElL_D9rOB?usp=sharing

![Peek 2021-09-09 09-32](https://user-images.githubusercontent.com/5016453/132695563-4aefea2f-03ff-4df4-bea5-4c4b12bdcd01.gif)

**Comment by giswqs** [comment]
OK, I can reproduce the error now. 

![Peek 2021-09-09 09-42](https://user-images.githubusercontent.com/5016453/132697007-ff4e1fd8-2858-44cc-9c03-1b271164c010.gif)

**Comment by crahan** [comment]
Interesting. Changing the `sandbox_path` is supposed to reset the filechooser, verify `sandbox_path` and `default_path` can work together (and throw an error if they are not aligned), and clear the current selection. I'll test some more, but in the meantime can you confirm you're testing with commit `6fc806b`?

Thanks again for helping to test this!

**Comment by giswqs** [comment]
Yes, I pulled the latest commit. You can test it here https://colab.research.google.com/drive/1C4GpAhe8_bKd14En3Kh975eElL_D9rOB?usp=sharing

**Comment by crahan** [comment]
The colab link seems to fail to run the `reset()` function. I tried calling `fc4.reset()` which should reset the filechooser to its original state, but that's not executing on the colab link you provided. Locally it appears to execute as expected.

As updating the `sandbox_path` value calls `reset()`, I'm thinking that's where things are failing. Below is a screen recording using similar initialization code as your example which tests both the `reset()` function and updating `sandbox_path`.

I'm somewhat baffled as to why it's failing.

https://user-images.githubusercontent.com/172588/132713695-b50ce3b5-16d6-4d92-926f-e555c8a370b1.mov

**Comment by giswqs** [comment]
It might be because Colab uses a different security model. Colab sometimes behaves differently than Jupyter notebook. This is not a big deal. As long as it works fine with Jupyter, we are good. I look forward to incorporating this into my packages once you have a new release. Many thanks for implementing this!

**Comment by crahan** [comment]
Is there any way for you to run a quick test on a local Jupyter notebook or lab instance just to confirm it's working well in that scenario?

**Comment by giswqs** [comment]
Yes, it works as expected. 

![Peek 2021-09-09 11-43](https://user-images.githubusercontent.com/5016453/132718503-aad92bb6-0dca-42d1-bd0e-37c410c09ae7.gif)

**Comment by crahan** [comment]
Thank you for confirming. I'm adding a few more smaller items like configurable folder icons and then I'll push out a new release. The release after that will focus on swapping out `os.path` for `pathlib` and writing some proper documentation.

**Comment by crahan** [comment]
v0.6.0 has been released and is now available from PyPi and Conda-forge. It includes the ability to restrict navigation up to a specific folder (by specifying a `sandbox_path`) and a number of additional enhancements and bug fixes. Please see https://github.com/crahan/ipyfilechooser/releases for details.

**Comment by giswqs** [comment]
Awesome! Thanks a lot for implementing this.
