### ISSUE TITLE
Creating a new file with an extension not in the allowed extension list

### ISSUE THREAD

**Issue by giswqs** [crahan/ipyfilechooser#38]
Thank you for implementing the filter pattern to allow multiple file extensions. It works like a charm! I would like to make a suggestion. If the user creates a new file with a file extension not in the allowed extension list, it is probably better to prompt the user the correct the file extension. If it is something difficult to implement, maybe changing the text color to red rather than the default green color would work. 

![](https://i.imgur.com/3PQmnLB.png)

**Comment by crahan** [comment]
Sounds good. I'll need to check what would be the easiest option to implement. I'll finish https://github.com/crahan/ipyfilechooser/issues/35 first and release a new version. Then pivot back to this.

**Comment by crahan** [comment]
The easiest way to solve this is by keeping the `select` or `change` button disabled unless the user specifies a filename that matches one of the configured filter patterns. For example, if the filter pattern is set to `['*.txt', '*.png']`, only filenames ending in `txt` or `png` will enable the button and allow the selection to be saved.

**Comment by giswqs** [comment]
Good solution. Thanks.

**Comment by crahan** [comment]
I'll include this in 0.4.3 together with the `top_folder` property that restricts navigation to a specific top folder. Should be available in the next day or 2.

**Comment by crahan** [comment]
Aplogies for the delay on implementing this and the `top_folder` fix. Unfortunatley, I had to focus on a more pressing matter. I'm picking this back up now.

**Comment by giswqs** [comment]
No problem. Thank you for your support.

**Comment by crahan** [comment]
Version 0.4.3 (https://github.com/crahan/ipyfilechooser/releases/tag/v0.4.3) now prevents the chosen filename from being applied when the name does not align with one of the `filter_pattern` values. PyPi and Conda-forge releases should now be available as well.
