### ISSUE TITLE
3 lines with "None" appears after the widget when running in jupyter

### ISSUE THREAD

**Issue by Trophime** [crahan/ipyfilechooser#39]
Hi,
trying to run in latest jupyter docker image the example you give to illustrate how to use ipyfilechoser I get 3 lines with "None"  
as can be seen here:
![FileChooser](https://user-images.githubusercontent.com/1309311/109000963-9fa46f80-76a4-11eb-8f31-9987b28adc8f.png)

Is there a way to get rid of these lines?
Best

**Comment by Trophime** [comment]
My bad. I haven't noticed the 3 print lines...
Sorry for the trouble.

**Comment by crahan** [comment]
No problem! Happy you found the solution!
