### ISSUE TITLE
events

### ISSUE THREAD

**Issue by majulier** [crahan/ipyfilechooser#4]
Is it possible to add a "changed" event so that I can register a callback for when the selected file (or folder) gets changed?  (or is there a way to do this already using the widgets framework?)

Thanks for the very useful widget!

**Comment by crahan** [comment]
All widgets already use a callback whenever a trait changes (filename, path dropdown, or file list) so changing that handler would most likely break the code. What I can try however is to allow you to specify a callback function of your own that I then execute at the end of the existing callback function for each widget.

I've got some time over the weekend to look into this in more detail and will also try and add a fix for https://github.com/crahan/ipyfilechooser/issues/3

As always, thank you for your feedback!

**Comment by crahan** [comment]
Hi @majulier, I'll close this in favor of https://github.com/crahan/ipyfilechooser/issues/6 which appears to be a similar request. I'll track all updates there.

**Comment by majulier** [comment]
That works for me. Thanks for your great work.
