### ISSUE TITLE
Extremely slow initialization

### ISSUE THREAD

**Issue by replork** [crahan/ipyfilechooser#40]
I am having trouble with the initialization of the FileChooser. Is it possible that I am doing something wrong or should I expect the original assignment of FileChooser to a variable to take > 80 seconds?

`import os`
`from ipyfilechooser import FileChooser`
`from time import time`
`cwd = os.getcwd()`
`start_time = time()`
`wb_path = FileChooser(cwd + "\\input")`
`print(f"FileChooser took {time() - start_time} seconds to init.")`
`start_time = time()`
`display(wb_path)`
`print(f"FileChooser took {time() - start_time} seconds to display.")`

![image](https://user-images.githubusercontent.com/36649598/113143378-12e85680-91fa-11eb-8366-6229450f8a80.png)

**Comment by giswqs** [comment]
It should not take this long to initialize. Are the many files under the directory?

**Comment by replork** [comment]
There is only 1 file in the directory, which is an Excel workbook (.xlsx),
and is only 31 KB in size. Additionally, the file is stored on an SSD which
is internal to the laptop.

**Comment by crahan** [comment]
This should indeed not take this long. I've run the test code you provided and it initialized almost instantly. I've tested this on Jupyter Lab version 2.2.0. 

![Screen Shot 2021-03-31 at 19 51 35](https://user-images.githubusercontent.com/172588/113188605-8a4dd280-925a-11eb-8f8f-4076f726e3b1.png)

**Comment by replork** [comment]
That is the response time that I would expect. I went ahead and tested it
again, and without any changes it has sped up considerably. I'm still only
getting it around 0.25, but I don't think that is a problem. I am using a
jupyter notebook, not jupyter lab. Could that have been the problem? I
didn't have anything expensive running at the time, but I guess this is
resolved. If it happens again, I will try to figure out what is causing it.
Many thanks.
