### ISSUE TITLE
Allow filter pattern to be case insensitive

### ISSUE THREAD

**Issue by giswqs** [crahan/ipyfilechooser#49]
The current filter pattern is case-sensitive. Do you think it makes sense to allow the filter pattern to be case insensitive? For example, `.filter_pattern = ["*.csv"]` finds all files with csv, Csv, and CSV extensions.

**Comment by crahan** [comment]
Good point, that should've been the default to be honest. I'll update!

**Comment by crahan** [comment]
Hi @giswqs, v0.4.4 has been released which makes `filter_pattern` case-insensitive (regardless of the operating system).

**Comment by giswqs** [comment]
Awesome! Thank you very much for the implementation.
