### ISSUE TITLE
Question for crahan: how do you debug/step through widget code?

### ISSUE THREAD

**Issue by maxshowarth** [crahan/ipyfilechooser#53]
Apologies for posting this as an issue, but wasn't sure how else I could ask...

Firstly, your widget is fantastic and thank you for supporting it.

I am trying to customize a portion of this widget for something I am building, but am struggling to de-bug it (and ipywidgets in general) as it gets more complicated. I have not found a way to add breakpoints, or step through the widget code and have resorted to print statements in the code to watch the flow of information.

I wanted to know if you had found a method for doing this, or had any suggestions on alternate methods?

**Comment by crahan** [comment]
Thank you for the kind words!

I'll have to disappoint you though. ipyfilechooser development and debugging has also been through print statements. I'd definitely love to find a better way to properly debug the widget (or any widget code for that matter) as `print()` only gets you so far.

In fact, I'm facing a similar issue with unit testing. I want to add some unit tests to the repo that Travis runs whenever a pull request is submitted to ensure the widget still works as expected, but I need to find a proper way to simulate UI interactions.

I'll leave this issue open and hopefully someone interested in this project stumbles across it and can help both of us with some good insights!

**Comment by giswqs** [comment]
Have you tried the JupyterLab debugger?
https://jupyterlab.readthedocs.io/en/stable/user/debugger.html
![](https://jupyterlab.readthedocs.io/en/stable/_images/step.gif)

**Comment by crahan** [comment]
That's amazing. I wasn't aware that existed! Thank you @giswqs!

**Comment by maxshowarth** [comment]
Thanks @crahan, this is what I had thought, but I was hopeful you may have had a solution!

@giswqs thank you for this! I have used this in the past, but my understanding is that breakpoints can only be set in code written in notebook cells, not in external files. I suppose it would be possible to do all the development in one massive notebook, which may be more convenient than relying on print statements alone.

Much appreciated!

**Comment by giswqs** [comment]
Breakpoints can be set for both notebook code and python scripts being called by the notebook

**Comment by crahan** [comment]
Thanks all for providing good input on this. I'll go ahead and close this issue.
