### ISSUE TITLE
allow passing full filepath as argument to FileChooser

### ISSUE THREAD

**Issue by gunstonej** [crahan/ipyfilechooser#55]
** Feature Request ** 

currently when you pass a full file path you get the following type of error:

![image](https://user-images.githubusercontent.com/21370980/128843118-d2f91ff6-0492-4496-b0e8-1b92b09a476a.png)

in my use case i have an interface that caches the previous user selection in a json file. 
when the app is relaunched ideally the previously selected path would still be the selected path. 

is this already possible?

**Comment by crahan** [comment]
You can't specify the path + file in a single string, but you can initialize a filechooser with both strings separately. If you don't mind splitting the stored JSON value into a path and filename string prior to initializing the filechooser object you can do the following:

```
fdialog = FileChooser(
    the_path,
    filename=the_file,
)
```

Alternatively filechooser objects allow retrieving the selected path and filename separately as well by using `fc.selected_path` and `fc.selected_filename`. You could also use those properties to store the selected path and filename separately in your JSON file and then use them in the example code snippet above to create a new filechooser with the previously selected value set as the default.

Hopefully one of those 2 options is a workable solution for you.

**Comment by gunstonej** [comment]
hi @crahan - 
thanks for the fast response! 

I had tried this approach... 
![image](https://user-images.githubusercontent.com/21370980/128851918-ed2fe38c-1cbc-4e43-911b-5f5c3b654f02.png)

which works in that it defaults to the filename you pass. 

...but - if i try and retrieve the: 

fc.selected_filename

it is empty until the user has actually pressed "select". 

the functionality i'd suggest is that the fc.selected_filename is already the file that is explicitly passed when calling the FileChooser class.

**Comment by crahan** [comment]
That is correct as it just sets the default selections and leaves the option to the user for applying the default or changing that selection first before confirming.

What you might want to try is initialize the filechooser object with the desired vales and then run `fc._apply_selection()` to apply the default values as the actual selection (which will close the dialog as a result). If the user still wants to change the selected value they can then use the `Change` button.

```
the_path = '/mnt/c/foo/bar'
the_file = 'myfile.csv'

fc = FileChooser(
    the_path,
    filename=the_file,
)

fc._apply_selection()
display(fc)
```

Hopefully that works better for your use case.

**Comment by gunstonej** [comment]
that does it - thanks very much!

**Comment by crahan** [comment]
Most welcome! Thanks for using ipyfilechooser!
