### ISSUE TITLE
Chooser should have propery, 'value' which returns same as 'selected'

### ISSUE THREAD

**Issue by tombelpasso** [crahan/ipyfilechooser#57]
Most ipywidgets have a 'value' attribute.  The 'selected' property naming makes sense for the chooser, but even drop down selectors have 'value' .

**Comment by crahan** [comment]
Thank you for the suggestion. This has now been added and pushed to the `width_and_fixes` branch. You can now use a `.value` property to return the same value as `.selected`. Please feel free to checkout the new branch and test.

**Comment by tombelpasso** [comment]
I tested the suggested branch and fc.value return None, while fc.selected returned the full file path.

Setting the width with fc.layout.width = 'auto' works.

Code:
# Print the selected path, filename, or both
print(fc.selected_path)
print(fc.selected_filename)
print(fc.selected)
print(fc.value)

Output:
C:\Portable\Documents\Python
laserRepairNew.ipynb
C:\Portable\Documents\Python\laserRepairNew.ipynb
None

**Comment by crahan** [comment]
I'm sorry, but I'm unable to replicate that issue. 

In any case, here's a recording using your sample code. As you can see, both `.selected` and `.value` return the proper value:

https://user-images.githubusercontent.com/172588/130286161-268d92b2-d5da-4a8d-94d2-2716ad0f52db.mov

**Comment by crahan** [comment]
v0.5.0 has now been published to PyPi. Conda-forge feedstock release will follow shortly. Thanks again for reporting this issue and helping to make the project better!
