### ISSUE TITLE
provide a way to register callback on selection file

### ISSUE THREAD

**Issue by shek2994** [crahan/ipyfilechooser#6]
Good. But need a way to register callback on selection file.

**Comment by crahan** [comment]
Hi @shek2994, could you give an example of what you would like to achieve? Are you looking for a callback function to be called whenever the user presses the `select` button?

**Comment by crahan** [comment]
As a quick test I've added a `register_callback(f)` function that takes a function name. When you select a file or a folder and then click the select/change button it will execute that function. 

@majulier, @shek2994 please let me know if that's what your were looking for. If it is then I'll push it and publish version 0.3.1.

**Comment by majulier** [comment]
Perfect.

**Comment by crahan** [comment]
Thanks for confirming, @majulier. Version 0.3.1 is now available on PyPi (https://pypi.org/project/ipyfilechooser/). I'll mark this issue as resolved.

**Comment by idrigo** [comment]
@crahan thanks for your work! 
Could you please help me, how to access callback function output. The return value from the callback function is written to the console, not to the cell output. Can you please fix it? Thanks!

**Comment by crahan** [comment]
Hi @idrigo, try using a callback class that has both the callback function and a variable that can store the value you would like to have returned or keep track of. In the below example, the `retval` variable is set to "Empty" when creating a CallBackClass object. Once the `callback_func` function is executed, the `retval` value will be set to "Hello world".

**Step 1**: create the callback class that has both the callback function and the variable to store what you want to track.
```
class CallBackClass:
    def __init__(self):
        self.retval = 'Empty'
    
    def callback_func(self, chooser):
        chooser.title = '<b>Callback function executed</b>'
        self.retval = 'Hello world' 
```

**Step 2**: initialize a CallBackClass object, and print its `retval` variable (you should see it print "Empty")
```
cb = CallBackClass()
print(cb.retval)
```

**Step 3**: register the callback function on your filechooser object.
```
fdialog.register_callback(cb.callback_func)
```

**Step 4**: select a file on the filechooser object to trigger the callback function.

**Step 5**: print the value of the `retval` variable again (you should now see it return "Hello world")
```
print(cb.retval)
```
