### ISSUE TITLE
How to make the widget resizable in Jupyter NB (programmatically and interactively)? 

### ISSUE THREAD

**Issue by richlysakowski** [crahan/ipyfilechooser#67]
The 'viewport' to select files and folder is too small for seeing enough files in many file systems.   

I need to set both height and width programmatically 

I could not find any programmatic settings in your code to modify it myself. 

Can you make create an argument to call it with a specific size in pixels or inches?  

RESIZE HANDLE: 

Having a "resize handle" in the lower right corner would be great for when the programmatically set size is still too small. 

Set Double-Click as Default for selection? 

Also, is there a way to set "double-click" as the default for selection?  
Single-click is too sensitive and does not conform to default expectations of most Windows and Mac users.

**Comment by crahan** [comment]
Thanks for submitting your feedback. It's much appreciated!

Unfortunately the resize interaction and double click behavior are not that easy to implement, but I 100% agree that the current implementation of the widget does not adhere to proper UX principles. The click/selection behavior is the result of how the `Select` widget handles input.

Selecting a custom size should not be an issue though. You can define the width of the widget in the same way you define a width value in CSS (e.g., %, px, em, etc) by using a `Layout` object. The height can be specified as a number of rows. Below is an example of an 80% width and 15 row height widget. Defining the width as a percentage also ensures the widget resizes as the browser window width changes:

```python
from ipyfilechooser import FileChooser
from ipywidgets import Layout
import os

# Create new FileChooser with an 80% width
fdialog = FileChooser(
    os.getcwd(),
    filename='test.txt',
    title='<b>FileChooser example</b>',
    select_default=True,
    layout=Layout(width='80%')
)

# Set the widget to a height of 15-rows
fdialog.rows = 15

# Display the widget
display(fdialog)
```

**Comment by richlysakowski** [comment]
Hi Thomas,

Wow, this is great!  Thank you so much.

You addressed my urgent need, which was resizing to the full width of the
filenames.   This makes it so much more usable!

Is there any way to pass through the other file and folder metadata, like
Fize Size and Creation Date, Modified Date ?

You inspired me to look much more into iPywidgets, which I have been
tip-toeing into for the past few years.

Thank you.

Best Regards,

Rich Lysakowski, Ph.D.
Data Scientist, Analytics Engineer,
and Senior Business Analyst
781-640-2048 mobile

**Comment by crahan** [comment]
Getting the metadata would be fairly trivial using `stat()`, but the issue is displaying it in the `Select` widget so it aligns the element name (file or folder) to the left and the metadata to the right in a series of columns. I'll dig around a bit to see if I find a way to make that work.
