### ISSUE TITLE
Option to render FileChooser as 'open' when loading

### ISSUE THREAD

**Issue by simbru** [crahan/ipyfilechooser#69]
Would it be possible to make the step of clicking 'select' to open the FileChooser optional? I feel this might be useful for applications where clicking select to open the widget is somewhat redundant.

**Comment by crahan** [comment]
Hi @simbru, It's not directly exposed via a parameter, but before you display the widget you can use the `_show_dialog()` function to open up the dialog:

```Python
fdialog = FileChooser(
    os.getcwd(),
    filename='test.txt',
    title='<b>FileChooser example</b>',
    show_hidden=False,
    select_default=True,
    show_only_dirs=False
)

fdialog._show_dialog()
display(fdialog)
```

Let me know if that helps resolve the issue for you or if you have any additional questions.

**Comment by simbru** [comment]
Hi @crahan, yes that's great! Exactly what I was looking for :) Thanks a bunch!

**Comment by crahan** [comment]
Awesome, thanks for confirming!
