### ISSUE TITLE
Why display(fc) return a string, not a real file chooser?

### ISSUE THREAD

**Issue by sunnysnowhi** [crahan/ipyfilechooser#71]
The output of fileChooser is like this：
![image](https://user-images.githubusercontent.com/52787424/182373943-009d5402-3749-46ff-8fc1-8f54fc326af4.png)

What's the problem?

**Comment by crahan** [comment]
Can you confirm that other widgets work as expected? Does the below code show a slider?

```python
import ipywidgets as widgets

widgets.IntSlider(
    value=7,
    min=0,
    max=10,
    step=1,
    description='Test:',
    disabled=False,
    continuous_update=False,
    orientation='horizontal',
    readout=True,
    readout_format='d'
)
```
