### ISSUE TITLE
does not work in python 3.10 - works fine in 3.9.5 (VSCode 1.7 )

### ISSUE THREAD

**Issue by jj-github-jj** [crahan/ipyfilechooser#73]
In VSCode, the ipyfilechooser works fine in python 3.9.5 but I also have 3.10 on my system and it does not show the widget in Python 3.1 version for some reason. 
here is the module list from python 3.10 where ipyfilechooser doesnt display anything
Package              Version
-------------------- ---------
asttokens            2.0.5
attrs                22.1.0
backcall             0.2.0
bleach               5.0.1
bokeh                2.4.3
certifi              2022.6.15
charset-normalizer   2.1.0
colorama             0.4.5
colorcet             3.0.0
colour               0.1.5
comtypes             1.1.11
cycler               0.11.0
debugpy              1.6.1
decorator            5.1.1
dominate             2.7.0
engineering-notation 0.6.0
entrypoints          0.4
et-xmlfile           1.1.0
executing            0.8.3
fastjsonschema       2.16.1
fonttools            4.34.4
holoviews            1.15.0
htap-jupyter-toolkit 0.0.394
hvplot               0.8.0
idna                 3.3
ipyfilechooser       0.6.0
ipykernel            6.15.0
ipython              8.4.0
ipywidgets           8.0.1
jedi                 0.18.1
Jinja2               3.1.2
jsonschema           4.15.0
jupyter-bokeh        3.0.4
jupyter-client       7.3.4
jupyter-core         4.10.0
jupyterlab-widgets   3.0.2
kiwisolver           1.4.4
Markdown             3.4.1
MarkupSafe           2.1.1
matplotlib           3.5.2
matplotlib-inline    0.1.3
metadict             0.1.2
nbformat             5.4.0
nest-asyncio         1.5.5
networkx             2.8.4
npTDMS               0.24.0
numpy                1.23.2
nxtdms               22.8.0.7
openpyxl             3.0.10
outlier-utils        0.0.3
packaging            21.3
pandas               1.4.2
panel                0.13.1
param                1.12.2
parso                0.8.3
pickleshare          0.7.5
Pillow               9.2.0
pip                  22.2.2
plotly               5.8.0
prompt-toolkit       3.0.30
psutil               5.9.1
pure-eval            0.2.2
pyct                 0.4.8
Pygments             2.12.0
pyparsing            3.0.9
pyrsistent           0.18.1
python-dateutil      2.8.2
pytz                 2022.1
pyviz-comms          2.2.0
pywin32              304
PyYAML               6.0
pyzmq                23.2.0
quantiphy            2.18.0
requests             2.28.1
scikit-rf            0.23.1
scipy                1.8.1
setuptools           58.1.0
six                  1.16.0
stack-data           0.3.0
tenacity             8.0.1
tornado              6.2
tqdm                 4.64.0
traitlets            5.3.0
typing_extensions    4.3.0
urllib3              1.26.10
wcwidth              0.2.5
webencodings         0.5.1
widgetsnbextension   4.0.2
xarray               2022.3.0
xlwt                 1.3.0

**Comment by crahan** [comment]
Thank you for reporting. I'll try and and test to see what's potentially causing this. There's another issue pending for a recent release of ipywidgets which breaks a few things which might be related as I see you have ipywidgets version 8.0.1 in your package list (https://github.com/crahan/ipyfilechooser/issues/72).

**Comment by crahan** [comment]
Apologies for the delay in responding. As noted on https://github.com/crahan/ipyfilechooser/issues/72, I tested this on a fresh Python 3.10.6 environment with the below package versions (including ipywidgets version 8.0.2) and the sample notebook code worked as expected in Jupyter Lab.

Can you please try upgrading to ipywidgets 8.0.2 to see if that fixes the issue you're experiencing?

![Screen Shot 2022-09-20 at 20 04 03](https://user-images.githubusercontent.com/172588/191333912-f5ac10b7-b68d-452c-ad28-e2b7735c752b.png)

```
Package              Version     Editable project location
-------------------- ----------- ------------------------------------------
anyio                3.6.1
appnope              0.1.3
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.8
attrs                22.1.0
Babel                2.10.3
backcall             0.2.0
beautifulsoup4       4.11.1
bleach               5.0.1
certifi              2022.6.15
cffi                 1.15.1
charset-normalizer   2.1.1
debugpy              1.6.3
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.4
executing            1.0.0
fastjsonschema       2.16.1
idna                 3.3
ipyfilechooser       0.6.0
ipykernel            6.15.2
ipython              8.4.0
ipython-genutils     0.2.0
ipywidgets           8.0.2
jedi                 0.18.1
Jinja2               3.1.2
json5                0.9.10
jsonschema           4.15.0
jupyter_client       7.3.5
jupyter-core         4.11.1
jupyter-server       1.18.1
jupyterlab           3.4.5
jupyterlab-pygments  0.2.2
jupyterlab_server    2.15.1
jupyterlab-widgets   3.0.3
lxml                 4.9.1
MarkupSafe           2.1.1
matplotlib-inline    0.1.6
mistune              2.0.4
nbclassic            0.4.3
nbclient             0.6.7
nbconvert            7.0.0
nbformat             5.4.0
nest-asyncio         1.5.5
notebook             6.4.12
notebook-shim        0.1.0
packaging            21.3
pandocfilters        1.5.0
parso                0.8.3
pexpect              4.8.0
pickleshare          0.7.5
pip                  22.2.2
prometheus-client    0.14.1
prompt-toolkit       3.0.31
psutil               5.9.1
ptyprocess           0.7.0
pure-eval            0.2.2
pycparser            2.21
Pygments             2.13.0
pyparsing            3.0.9
pyrsistent           0.18.1
python-dateutil      2.8.2
pytz                 2022.2.1
pyzmq                23.2.1
requests             2.28.1
Send2Trash           1.8.0
setuptools           63.2.0
six                  1.16.0
sniffio              1.3.0
soupsieve            2.3.2.post1
stack-data           0.5.0
terminado            0.15.0
tinycss2             1.1.1
tornado              6.2
traitlets            5.3.0
urllib3              1.26.12
wcwidth              0.2.5
webencodings         0.5.1
websocket-client     1.4.0
widgetsnbextension   4.0.3
```
