### ISSUE TITLE
Folder view not showing in VSCODE

### ISSUE THREAD

**Issue by fyakghoon2266** [crahan/ipyfilechooser#74]
I use FileChooser in python3.7, although no error is displayed, but the window for selecting data is not displayed.
![image](https://user-images.githubusercontent.com/95900753/193244959-b4ef3f97-3b40-44fc-9555-ff09b887cf83.png)

Is it because my vscode environment is not set up?

Thanks!

**Comment by dcavar** [comment]
Same here in multiple different configurations...

**Comment by crahan** [comment]
I've not tested this in a VS Code environment unfortunately. Only in Jupyter Lab.

**Comment by simplethemind** [comment]
I got it to work by following a recommendation from this discussion:
[https://stackoverflow.com/questions/68500861/visual-studio-code-does-not-render-ipywidgets-correctly](url)

Replacing the latest ipywidgets with version 7.7.1 did the trick for me.
`pip install -U ipywidgets==7.7.1`

**Comment by crahan** [comment]
Thank you for delving into this and finding a solution!

**Comment by fyakghoon2266** [comment]
Thank for everyone
